version: "3"

services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile.hugo
    ports:
      - "1313:1313"
    volumes:
      - ".:/usr/src/app"

  ruby:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    volumes:
      - ".:/usr/src/app"
